### ISSUE TITLE
Package built binary as OCI images, push to GitHub Container Registry

### ISSUE THREAD

**Issue by mathetake** [istio-ecosystem/wasm-extensions#69]
Then we can leverage these built OCI images in the Istio tests (in addition to the fake ones as I did in the unit tests https://github.com/istio/istio/blob/master/pkg/wasm/imagefetcher_test.go#L80-L103). I've already done this in Proxy-Wasm Go SKD repository (https://github.com/orgs/tetratelabs/packages/container/package/proxy-wasm-go-sdk-examples).

Note that GHCR is free for OSS projects as long as the registry is public.

I can take care of this if it's ok. wdyt? @bianpengyuan

**Comment by mathetake** [comment]
or maybe better push the extensions in istio/proxy rather than extensions here.

**Comment by bianpengyuan** [comment]
Yeah this sounds great! We should push the extensions as OCI both at istio proxy and here. For testing, we should use the ones shipped from istio proxy. The integration test at istio/istio is already using MX, stats, and attribute-gen Wasm extensions, we should just switch to OCI image in those test.

**Comment by mathetake** [comment]
OK cool, so could you give me the write permission for this repository so I can push the images from the GHA running on branches in this repo (!= on my fork)?

as for istio/proxy, let me try by using the same credential used there for pushing proxyv2 images.

**Comment by bianpengyuan** [comment]
> OK cool, so could you give me the write permission for this repository so I can push the images from the GHA running on branches in this repo (!= on my fork)?

Just sent you the invitation.

> as for istio/proxy, let me try by using the same credential used there for pushing proxyv2 images.

Yep, it should be pushed to istio-testing gcr.
