### ISSUE TITLE
Issue with grpc_logging example

### ISSUE THREAD

**Issue by wesleyhales** [istio-ecosystem/wasm-extensions#70]
Hi - I tried to compile the grpc logging example and received the following error:
`wasm_compile_log_1     | In file included from examples/wasm-cc/plugin.cc:1:
wasm_compile_log_1     | examples/wasm-cc/plugin.h:1:10: fatal error: 'extensions/grpc_logging/config.pb.h' file not found
wasm_compile_log_1     | #include "extensions/grpc_logging/config.pb.h"
wasm_compile_log_1     |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
wasm_compile_log_1     | 1 error generated.`

Are there files missing? or am I doing something wrong? Thanks!

**Comment by bianpengyuan** [comment]
How did you compile it?

**Comment by wesleyhales** [comment]
I replaced the source in the envoy example here with grpc_logging:
https://github.com/envoyproxy/envoy/tree/main/examples/wasm-cc

Should I compile it differently? what is the best way to do a simple test on envoy?
