### ISSUE TITLE
Help required for deploying basic auth wasm extension

### ISSUE THREAD

**Issue by rahulanand16nov** [istio-ecosystem/wasm-extensions#72]
Hi there maintainers,

I was trying to deploy the [basic auth wasm module](https://raw.githubusercontent.com/istio-ecosystem/wasm-extensions/master/extensions/basic_auth/config/gateway-filter.yaml) on Istio 1.12.0-beta with book info workload but failed to do so. Can anyone point me to where I am making a mistake? I did the following:

1. create [kind](https://kind.sigs.k8s.io/) cluster
```
kind create cluster
```
2. install istio components to istio-system namespace
```
istioctl install -y
```
3. label default namespace for automatic injection of sidecar proxies
```
kubectl label namespace default istio-injection=enabled
```
```
kubectl apply -f [bookinfo.yaml](https://raw.githubusercontent.com/istio/istio/release-1.11/samples/bookinfo/platform/kube/bookinfo.yaml)

kubectl apply -f [bookinfo-gateway.yaml](https://raw.githubusercontent.com/istio/istio/release-1.11/samples/bookinfo/networking/bookinfo-gateway.yaml)

kubectl apply -f [gateway-filter.yaml](https://raw.githubusercontent.com/istio-ecosystem/wasm-extensions/master/extensions/basic_auth/config/gateway-filter.yaml)
```

curl to /productpage seems to be same before and after applying the filter. What am I missing here?

**Comment by maleck13** [comment]
+1 it would be great to have an example to try out. Difficult to understand where we are going wrong at the moment

**Comment by bianpengyuan** [comment]
The gateway-filter.yaml you applied selects only 1.11 proxies. Please follow the official guide for how to deploy the basic auth filter: https://istio.io/latest/docs/ops/configuration/extensibility/wasm-module-distribution/
