### ISSUE TITLE
grpc_logging example  get request body

### ISSUE THREAD

**Issue by clarechu** [istio-ecosystem/wasm-extensions#82]
hi!  how to get a request body in the grpc_logging example .

```c
std::string request_body;
getValue({"response", "body"}, &request_body);

```

Can I get it this way?

**Comment by bianpengyuan** [comment]
You will need to use getbuffer: https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/9af5ac0145a8790f62ca501c43f6fa1ea24d2d93/proxy_wasm_common.h#L90
